
server:
  port: 5556

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://database-1.cnewefifpzkk.ap-southeast-1.rds.amazonaws.com:5432/test1?user=postgres&password=bFrphP7kjUS1KqHOhM6U&sslmode=require
  jpa:
    show-sql: true
    generate-ddl: true
    #    add below config for bug in springfox-boot-starter, consider migrate to springdoc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  activemq:
    #    user: admin
    #    password: admin
    #    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
      max-connections: 50
    packages:
      trust-all: true
  jms:
    pub-sub-domain: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: anchiao0417@gmail.com
    password: vgansukkzdfpxagi
#    username: f29469581@gmail.com
#    password: qclyllkuqfzqrtln
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
camel:
  springboot:
    xml-routes: classpath:./spring/camel-context.xml

logging:
  file:
    name: logs/notification-service.log