server:
  port: 5555

spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://database-1.cnewefifpzkk.ap-southeast-1.rds.amazonaws.com:5432/test1?user=postgres&password=bFrphP7kjUS1KqHOhM6U&sslmode=require
  jpa:
    show-sql: true
    generate-ddl: true
    #    add below config for bug in springfox-boot-starter, consider migrate to springdoc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: iso
  activemq:
#    user: admin
#    password: admin
#    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
      max-connections: 50
    packages:
      trust-all: true
  jms:
    pub-sub-domain: false

logging:
  file:
    name: logs/expense-service.log
